### PR TITLE
Fixing waiver handler and signing process

### LINKED ISSUE #273: [Portal] Waiver signing process lacks clarity
A small but noticeable proportion of accepted applicants signed the waiver more than once, likely thinking the submission was not received since the DocuSign Connect webhook can have a slight delay. Additionally, several participants have signed the waiver but not confirmed their attendance.
- Open the waiver signing form in a new tab
- Include a message that it may take a minute or so for the waiver completion to be recognized
- Use a client-side hook with SWR to refetch the user's status when refocusing the window/tab with the Portal

### PR DESCRIPTION
**Pull request by Bl20052005**
Closes #273 and #317

### CODE REVIEW

**Review by waalbert — APPROVED** [review]
Looking awesome Bo!

File: apps/site/src/app/(main)/portal/@applicant/ApplicantPortal.tsx [hunk 1]
```diff
@@ -25,15 +27,15 @@ export const enum PortalStatus {
...
+	const identity = useUserIdentity();
+	const status = identity?.status;
 
 	if (status === null) {
 		redirect("/#apply");
 	}
 
-	const roleToDisplay = identity.roles.find((role) =>
+	const roleToDisplay = identity?.roles.find((role) =>
 		rolesArray.includes(role),
```
[the remark this answers is not in the document]
Comment (taesungh) [reply apps/site/src/app/(main)/portal/@applicant/ApplicantPortal.tsx:39]: Oh I see, `identity`is initially undefined. In that case, it would be good to display a loading state or perhaps provide the initial value from the server (subject to downsides noted in #523).

File: apps/api/src/utils/waiver_handler.py [hunk 2]
```diff
@@ -38,6 +38,9 @@ async def process_waiver_completion(uid: str, email: EmailStr) -> None:
                 f"User {uid} attempted to sign waiver but already signed it previously."
             )
             return
+        elif applicant_record.status == Status.ATTENDING:
+            log.warning(f"User {uid} has already signed the waiver and is attending.")
+            return
```
Comment (taesungh) [inline apps/api/src/utils/waiver_handler.py:43]: Sorry I missed this before, but I think this condition could be combined with the one before on line 36. For the future, might be worth considering somehow making `Status` a partially ordered set.

Comment (Bl20052005) [reply apps/api/src/utils/waiver_handler.py:43]: It definitely could, I just thought that the warning message here is different enough to the previous one
