### PR TITLE
Minor UI changes

### LINKED ISSUE #481: Increase size of volunteer availability input boxes on mobile
In relation to #477 to improve the accessibility and UI of the volunteer apps, notably the availability input fields, the volunteer availability input fields needs to be larger on mobile for easier use. With the current size of these input fields, the user can easily click the wrong input field.

### LINKED ISSUE #488: Move pronouns question to left on mentor app
On hacker and volunteer apps, the pronouns question is on the left side of the form, while the pronouns question for the mentor app is in the center. For consistency, let's move the pronouns question on the mentor app to the left.

### LINKED ISSUE #489: Fix spacing between app title and apps close
On smaller screen widths, the "Apply to be a ..." title and "Applications close ..." section are squished.

### LINKED ISSUE #494: Default button doesn't transition out of hover

### LINKED ISSUE #497: Specify word limit on hacker apps FRQs
Due to confusion with the current wording of the word limit for the hacker apps' FRQs, update the text to say, for example, "100+ words recommended" rather than "100 words."

### PR DESCRIPTION
**Pull request by IanWearsHat**
Moved transition out of hover state for button, closes #494 

Fixed spacing between app title and apps close in `Title` component, closes #489 

Made pronouns question full width in Mentor apps, closes #488

Increased height of each DayShift choice box, closes #481 

Clarified word suggestion for Hacker app, closes #497 

Also changed spacing for `ConfirmationDetails` component for mobile views

### CODE REVIEW

File: apps/site/src/app/(main)/volunteer/components/DayShift.tsx [hunk 1]
```diff
@@ -88,7 +88,7 @@ export default function DayShift({
 								{as12Hour(startHour + i)}
 							</div>
 							<div
-								className={`h-[30px] w-full ${
+								className={`h-[50px] md:h-[30px] w-full ${
```
Comment (waalbert) [inline apps/site/src/app/(main)/volunteer/components/DayShift.tsx:91]: Can you make the input height slightly bigger?

File: apps/site/src/lib/components/Button/Button.module.scss [hunk 2]
```diff
@@ -13,10 +13,13 @@
...
-	&:hover > .button {
+	& > .button {
 		transition: all 0.15s ease-out;
-		transform: translate(-8px, -8px);
-		filter: brightness(1.05);
+
+		&:hover {
+			transform: translate(-8px, -8px);
+			filter: brightness(1.05);
+		}
```
Comment (waalbert) [inline apps/site/src/lib/components/Button/Button.module.scss:22]: Hover effect is a bit glitchy when mouse is moved with the Button moving back down to its original position and animating back up

**Review by waalbert — COMMENTED** [review]
Can you also handle #497 as well?

**Review by waalbert — APPROVED** [review]
Thanks for these quick UI fixes Ian!
